config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :lists, only: %I[index show new create destroy] do
    resources :marks, only: %I[new create]
  end
  resources :musics, only: %I[new create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
  has_many :musics
end

app/models/list.rb
class List < ApplicationRecord
  # @name
  # @style

  has_one_attached :photo

  belongs_to :user
  has_many :marks, dependent: :destroy
  has_many :musics, through: :marks

  validates :name, presence: true, uniqueness: true
  validates :style, presence: true

  STYLE = %w[classic rock pop rap electro autres...]
end

app/models/mark.rb
class Mark < ApplicationRecord
  belongs_to :list
  belongs_to :music

  validates :music_id, presence: true
end

app/models/music.rb
class Music < ApplicationRecord
  has_many :marks, dependent: :destroy
  has_many :lists, through: :marks
  belongs_to :author

  validates :title, presence: true
  validates :author, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # @email
  # @username

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :lists

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :authenticate_user!

  def index
    @lists = List.includes(:user)
  end

  def show
    @list = List.find(params[:id])
    @musics = Mark.where(list_id: @list.id)
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    @list.user_id = current_user.id
    if @list.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  def destroy
    @list = List.find(params[:id])
    @list.destroy
    redirect_to lists_path
  end

  private

  def list_params
    params.require(:list).permit(:name, :style, :photo)
  end
end

app/controllers/marks_controller.rb
class MarksController < ApplicationController

  def new
    @list = List.find(params[:list_id])
    @mark = Mark.new
    @musics = Music.all.uniq
  end

  def create
    @mark = Mark.new(mark_params)
    @mark.list_id = params[:list_id]
    @mark.save
    redirect_to list_path(params[:list_id])
  end

  private

  def mark_params
    params.require(:mark).permit(:music_id)
  end
end

app/controllers/musics_controller.rb
class MusicsController < ApplicationController

  def new
    @music = Music.new
  end

  def create
    @authors = Author.all
    @music = Music.new(music_params)
    if @music.save
      redirect_to lists_path
    else
      render :new
    end
  end

  private

  def music_params
    params.require(:music).permit(:title, :author_id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :authenticate_user!, except: :home

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Spotynoob</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/lists/index.html.erb
<h1>List#index</h1>

<%= link_to "New Playlist", new_list_path, class:"btn btn-success" %>
<%= link_to "New Music", new_music_path, class:"btn btn-info" %>

<div class="row d-flex justify-content-around">
  <% @lists.reverse.each do |list| %>
    <div class="card mx-2 my-2" style="width: 18rem;">
      <div class="card-body">
        <% if list.photo.attached? %>
          <%= cl_image_tag list.photo.key, height: 200, width: 250, crop: :fill %>
          <% else %>
          <%= image_tag('https://res.cloudinary.com/drndiy1wn/image/upload/v1639402451/paknbpy0fnfdvoizh4q2.jpg', height: 200, width: 250, crop: :fill) %>
        <% end %>
        <h5 class="card-title"><%= link_to list.name, list_path(list.id) %></h5>
        <p class="card-text"><%= list.style %></p>
        <p class="card-text"><%= list.user.username %></p>
      </div>
    </div>
  <% end %>
</div>

app/views/lists/new.html.erb
<h1>new#list</h1>

<%= simple_form_for @list do |f| %>
  <div class="form">
    <%= f.input :name, placeholder: 'Playlist name' %>
    <%= f.input :style, collection: List::STYLE %>
    <%= f.input :photo, as: :file %>
    <div class="submit">
      <%= f.submit class: 'btn btn-primary' %>
      <%= link_to "Back to index", lists_path, class:"btn btn-info" %>
    </div>
  </div>
<% end %>

app/views/lists/show.html.erb
<h1>list#show</h1>
<h2><%= @list.name %></h2>
<% if @list.photo.attached? %>
  <%= cl_image_tag @list.photo.key, height: 300, width: 400, crop: :fill %>
<% end %>
<h2><%= @list.user.username %></h2>

<ul>
  <% @musics.reverse.each do |mark| %>
    <li><%= mark.music.title %></li>
  <% end %>
</ul>


<%= link_to "Delete", list_path(@list), method: :delete, class: "btn btn-danger" %>
<%= link_to "Add Music", new_list_mark_path(@list), class: "btn btn-success" %>

app/views/marks/new.html.erb
<h1>new#mark</h1>

<%= simple_form_for [@list, @mark] do |f| %>
  <div class="form">
    <%= f.input :music_id, collection: @musics %>
    <%= f.submit %>
  </div>
<% end %>

app/views/musics/new.html.erb
<h1>new#music</h1>

<%= simple_form_for @music do |f| %>
  <div class="form">
    <%= f.input :author_id, collection: Author.all, :label_method => :name, :value_method => :id %>
    <%= f.input :title, placeholder: 'Track name' %>
    <div class="submit">
      <%= f.submit class: 'btn btn-primary' %>
      <%= link_to "Back to index", lists_path, class:"btn btn-info" %>
    </div>
  </div>
<% end %>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "#", class: "navbar-brand" do %>
    <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", root_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Index", lists_path, class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Action", "#", class: "dropdown-item" %>
            <%= link_to "Another action", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>